x-postgres-config: &postgres-config
  POSTGRES_HOST: core-db
  POSTGRES_DB: gorm
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432

services:
  storescp:
      environment:  
        ADDITIONAL_CORES: "core1"

  core1:
      image: "milvue/pacsor-core:${DOCKER_IMAGE_TAG:?give a valid tag of image to pull}"
      environment:
        GOMAXPROCS: 0
        PROFILER: true
        SIGNED_URL: ${SIGNED_URL:-true}
        API_URL: ${API_URL_1:?need valid URL}
        TOKEN: ${TOKEN_1:?can't be empty}
        CALLBACK_URLS: ${CALLBACK_URLS_1:?can't be empty}
        INFERENCE_COMMANDS: ${INFERENCE_COMMANDS_1:-smarturgences,smartxpert}
        <<: *postgres-config
      depends_on:
        core-db:
          condition: service_healthy
        core:
          condition: service_healthy
      restart: always
      volumes:
          - inputs:/inputs
          - outputs:/outputs
      healthcheck:
        test: [ "CMD", "./healthcheck" ]
        interval: 5s
        timeout: 5s
        retries: 10
      networks:
        - pacsor
