x-postgres-config: &postgres-config
  POSTGRES_HOST: core-db
  POSTGRES_DB: gorm
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432
  
services:
  storescp-beta:
    image: "milvue/pacsor-storescp-wgs:${DOCKER_IMAGE_TAG:?give a valid tag of image to pull}"
    ports:
      - "${PORT_BETA:-1050}:1040"
    restart: always
    environment:
      CORE_HOST: "${CORE_NAME:-core-beta}"
      CONFIG_PROFILE: ${CONFIG_PROFILE:-WithSC}
      LOG_LEVEL: ${PACSOR_LOG_LEVEL:-warn}
    volumes:
      - inputs:/inputs
      - type: bind
        source: "../conf/filter.cfg"
        target: /filter.cfg
    healthcheck:
      test: [ "CMD-SHELL", "echoscu -v storescp 1040" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pacsor

  core-beta:
    image: "milvue/pacsor-core:${DOCKER_IMAGE_TAG:?give a valid tag of image to pull}"
    environment:
      GOMAXPROCS: 0
      PROFILER: true
      SIGNED_URL: ${SIGNED_URL:-true}
      API_URL: ${API_URL_BETA:?need valid URL}
      TOKEN: ${TOKEN_BETA:?can't be empty}
      CALLBACK_URLS: ${CALLBACK_URLS:-http://storescu:8000}
      NO_DUPLICATE_UPLOAD: ${NO_DUPLICATE_UPLOAD:-true}
      <<: *postgres-config
    depends_on:
      core-db:
        condition: service_healthy
      core:
        condition: service_healthy
    restart: always
    volumes:
        - inputs:/inputs
        - outputs:/outputs
    healthcheck:
      test: [ "CMD", "./healthcheck" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pacsor